version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - dotnet restore TrodoDataExporter/TrodoDataExporter.csproj
  build:
    commands:
      - dotnet build TrodoDataExporter/TrodoDataExporter.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/TrodoDataExporter/TrodoDataExporter.csproj
artifacts:
  files:
    - '**/*'